steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/indu-1234/r/suryansh-saisree']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}']

substitutions:
  _IMAGE_NAME: aradhya_image  # Adjusted to follow the naming convention
  _SHORT_SHA: v1.0
  _PROJECT_ID: indu-1234
